[package]
name = "elevate"
version = "0.8.1"
authors = ["Starz0r <starz0r@starz0r.com>"]

[dependencies]
winapi = { version = "0.3.4", features = ["winbase", "shellapi", "winuser", "synchapi"] }
winutil = "0.1.1"
named_pipe = "0.2.4"

[features]
default = ["std"]
std = ["winapi/std"]
